#!/usr/bin/env python3

import click
import sys

import domain_entity
import domain_alias_entity
import mapping_entity


@click.group()
@click.option("--url", "-u", default="http://127.0.0.1", show_default=True, help="Set url address")
@click.option("--port", "-p", default="8000", show_default=True, help="Set port")
@click.pass_context
def main(ctx, url, port):
    """Run './james_cli COMMAND --help' for more information on a command."""
    path = url + ":" + port
    ctx.obj = {
        "path": path
    }


main.add_command(domain_entity.domain)
main.add_command(domain_alias_entity.domain_alias)
main.add_command(mapping_entity.mapping)


if __name__ == "__main__":
    main()
