<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements. See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership. The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<!--
    Tag order follows model description at http://maven.apache.org/ref/3.0.3/maven-model/maven.html
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>james-project</artifactId>
        <groupId>org.apache.james</groupId>
        <version>1.8.3-SNAPSHOT</version>
    </parent>

    <artifactId>james-server</artifactId>
    <version>3.0.0-beta5-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Apache James :: Server</name>
    <description>Apache James Mail Server</description>
    <url>http://james.apache.org/server/head/</url>
    <inceptionYear>2002</inceptionYear>

    <repositories>
        <!-- apache.snapshot is needed for james-project SNAPSHOT, see JAMES-1470 -->
        <repository>
            <id>apache.snapshots</id>
            <name>Apache Snapshot Repository</name>
            <url>http://repository.apache.org/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>

    <modules>
        <module>protocols/jmap-integration-testing</module>
        <module>testcontainers-java/core</module>
        <module>docker-java</module>
    </modules>

    <distributionManagement>
        <site>
            <id>server-trunk-website</id>
            <url>scpexe://people.apache.org/www/james.apache.org/server/3/</url>
        </site>
    </distributionManagement>

    <properties>
        <productName>Apache-James Mail Server</productName>

        <slf4j.version>1.7.2</slf4j.version>

        <junit.version>4.11</junit.version>
        <log4j.version>1.2.17</log4j.version>
        <guava.version>16.0</guava.version>
        <assertj-3.version>3.3.0</assertj-3.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.james</groupId>
                <artifactId>testcontainers</artifactId>
                <version>3.0.0-beta5-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.james</groupId>
                <artifactId>docker-java</artifactId>
                <version>3.0.0-beta5-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>org.apache.james</groupId>
                <artifactId>james-server-jmap-integration-testing</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>jcl-over-slf4j</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${slf4j.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
            </dependency>

            <dependency>
                <groupId>log4j</groupId>
                <artifactId>log4j</artifactId>
                <version>${log4j.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.0</version>
            </plugin>
            <plugin>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <!-- During release:perform, enable the "release" profile -->
                    <releaseProfiles>with-assembly</releaseProfiles>
                    <goals>deploy assembly:single</goals>
                </configuration>
            </plugin>
        </plugins>
        <pluginManagement>
          <plugins>
            <!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
            <plugin>
              <groupId>org.eclipse.m2e</groupId>
              <artifactId>lifecycle-mapping</artifactId>
              <version>1.0.0</version>
              <configuration>
                <lifecycleMappingMetadata>
                  <pluginExecutions>
                    <pluginExecution>
                      <pluginExecutionFilter>
                        <groupId>org.ops4j.pax.exam</groupId>
                        <artifactId>maven-paxexam-plugin</artifactId>
                        <versionRange>[1.2.4,)</versionRange>
                        <goals>
                          <goal>generate-config</goal>
                          <goal>generate-depends-file</goal>
                        </goals>
                      </pluginExecutionFilter>
                    </pluginExecution>
                  </pluginExecutions>
                </lifecycleMappingMetadata>
              </configuration>
            </plugin>
          </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <!-- run live tests, ie. ones that do not run stably enough in
            a CI environment (for example, karaf integration tests accessing external network
            resources) -->
            <id>livetests</id>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <includes>
                                <include>**/*TestLive.java</include>
                            </includes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
